myartists/templates/urls.py
from django.conf.urls import patterns, url
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView

from models import Artist, Album
from forms import ArtistForm, AlbumForm
from views import ArtistCreate, AlbumCreate, ArtistDetail

urlpatterns = patterns('',
    # List latest 5 artists: /myartists/
    url(r'^$',
        ListView.as_view(
            queryset=Artist.objects.filter(date__lte=timezone.now()).order_by('date')[:5],
            context_object_name='latest_artist_list',
            template_name='myartists/artist_list.html'),
        name='artist_list'),

    # Artist details, ex.: /myartists/artists/1/
    url(r'^artists/(?P<pk>\d+)/$',
        ArtistDetail.as_view(),
        name='artist_detail'),

    # Create a artist: /myartists/artists/create/
    url(r'^artists/create/$',
        ArtistCreate.as_view(),
        name='artist_create'),

    # Edit artist details, ex: /myartists/artists/1/edit/
    url(r'^artists/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Artist,
            form_class=ArtistForm,
            template_name='myartists/form.html'),
        name='artist_edit'),

    # Artist album details, ex: /myartists/artists/1/albums/1/
    url(r'^artists/(?P<pkr>\d+)/albums/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Album,
            template_name='myartists/album_detail.html'),
        name='album_detail'),

    # Create a artist album, ex: /myartists/artists/1/albums/create/
    url(r'^artists/(?P<pk>\d+)/albums/create/$',
        AlbumCreate.as_view(),
        name='album_create'),

    # Edit artist album details, ex: /myartists/artists/1/albums/1/edit/
    url(r'^artists/(?P<pkr>\d+)/albums/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Album,
            form_class=AlbumForm,
            template_name='myartists/form.html'),
        name='album_edit'),

    # Create a artist review using function, ex: /myartists/artists/1/reviews/create/
    url(r'^artists/(?P<pk>\d+)/reviews/create/$',
        'myartists.views.review',
        name='review_create'),
)

myartists/urls.py
from django.conf.urls import patterns, url
from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView

from models import Artist, Album
from forms import ArtistForm, AlbumForm
from myartists.views import ArtistCreate, AlbumCreate, ArtistDetail


urlpatterns = patterns('',
    # List latest 5 artists: /myartists/
    url(r'^$',
        ListView.as_view(
            queryset=Artist.objects.filter(date__lte=timezone.now()).order_by('date')[:5],
            context_object_name='latest_artist_list',
            template_name='myartists/artist_list.html'),
        name='artist_list'),

    # Artist details, ex.: /myartists/artists/1/
    url(r'^artists/(?P<pk>\d+)/$',
        ArtistDetail.as_view(),
        name='artist_detail'),

    # Create a artist: /myartists/artists/create/
    url(r'^artists/create/$',
        ArtistCreate.as_view(),
        name='artist_create'),

    # Edit artist details, ex: /myartists/artists/1/edit/
    url(r'^artists/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Artist,
            form_class=ArtistForm,
            template_name='myartists/form.html'),
        name='artist_edit'),

    # Artist album details, ex: /myartists/artists/1/albums/1/
    url(r'^artists/(?P<pkr>\d+)/albums/(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Album,
            template_name='myartists/album_detail.html'),
        name='album_detail'),

    # Create a artist album, ex: /myartists/artists/1/albums/create/
    url(r'^artists/(?P<pk>\d+)/albums/create/$',
        AlbumCreate.as_view(),
        name='album_create'),

    # Edit artist album details, ex: /myartists/artists/1/albums/1/edit/
    url(r'^artists/(?P<pkr>\d+)/albums/(?P<pk>\d+)/edit/$',
        UpdateView.as_view(
            model=Album,
            form_class=AlbumForm,
            template_name='myartists/form.html'),
        name='album_edit'),

    # Create a artist review using function, ex: /myartists/artists/1/reviews/create/
    url(r'^artists/(?P<pk>\d+)/reviews/create/$',
        'myartists.views.review',
        name='review_create'),
)

myrecommendations/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myrecommendations.views.home', name='home'),
    # url(r'^myrecommendations/', include('myrecommendations.foo.urls')),

    url(r'^myartists/', include('myartists.urls', namespace='myartists')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
        )

myartists/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date

class Artist(models.Model):
    name = models.TextField()
    city = models.TextField(default="")
    country = models.TextField(blank=True, null=True)
    style = models.TextField(blank=False)
    web = models.URLField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('myartists:artist_detail', kwargs={'pk': self.pk})


class Album(models.Model):
    name = models.TextField()
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField('Euro amount', max_digits=8, decimal_places=2, blank=True, null=True)
    image = models.ImageField(upload_to="myartists", blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)
    artist = models.ForeignKey(Artist, null=True, related_name='albums')

    def __unicode__(self):
        return u"%s" % self.name
    def get_absolute_url(self):
        return reverse('myartists:album_detail', kwargs={'pkr': self.artist.pk, 'pk': self.pk})

class Review(models.Model):
    RATING_CHOICES = ((1,'1'),(2,'2'),(3,'3'),(4,'4'),(5,'5'))
    rating = models.PositiveSmallIntegerField('Ratings (stars)', blank=False, default=3, choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, default=1)
    date = models.DateField(default=date.today)

    class Meta:
        abstract = True

class ArtistReview(Review):
    artist = models.ForeignKey(Artist)

myartists/forms.py
from django.forms import ModelForm
from myartists.models import Artist, Album

class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        exclude = ('user', 'date',)

class AlbumForm(ModelForm):
    class Meta:
        model = Album
        exclude = ('Artist', 'user', 'date',)

myartists/templates/views.py
# Create your views here.

from django.core import urlresolvers
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView

from models import ArtistReview, Artist, Album
from forms import ArtistForm, AlbumForm

class ArtistDetail(DetailView):
    model = Artist
    template_name = 'myartists/artist_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ArtistDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = ArtistReview.RATING_CHOICES
        return context

class ArtistCreate(CreateView):
    model = Artist
    template_name = 'myartists/form.html'
    form_class = ArtistForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArtistCreate, self).form_valid(form)

class AlbumCreate(CreateView):
    model = Album
    template_name = 'myartists/form.html'
    form_class = AlbumForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.artist = Artist.objects.get(id=self.kwargs['pk'])
        return super(AlbumCreate, self).form_valid(form)

def review(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    new_review = ArtistReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        artist=artist)
    new_review.save()
    return HttpResponseRedirect(urlresolvers.reverse('myartists:artist_detail', args=(artist.id,)))

myartists/views.py
# Create your views here.

from django.core import urlresolvers
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView

from myartists.models import ArtistReview, Artist, Album
from forms import ArtistForm, AlbumForm


class ArtistDetail(DetailView):
    model = Artist
    template_name = 'myartists/artist_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ArtistDetail, self).get_context_data(**kwargs)
        context['RATING_CHOICES'] = ArtistReview.RATING_CHOICES
        return context

class ArtistCreate(CreateView):
    model = Artist
    template_name = 'myartists/form.html'
    form_class = ArtistForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ArtistCreate, self).form_valid(form)

class AlbumCreate(CreateView):
    model = Album
    template_name = 'myartists/form.html'
    form_class = AlbumForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.artist = Artist.objects.get(id=self.kwargs['pk'])
        return super(AlbumCreate, self).form_valid(form)

def review(request, pk):
    artist = get_object_or_404(Artist, pk=pk)
    new_review = ArtistReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        artist=artist)
    new_review.save()
    return HttpResponseRedirect(urlresolvers.reverse('myartists:artist_detail', args=(artist.id,)))

myartists/templates/myartists/album_detail.html
{% extends "myrecommendations/base.html" %}

{% block content %}

<h1>
    {{ album.name }}
    {% if user == album.user %}
        (<a href="{% url 'myrecommendations:album_edit' album.artist.id album.id %}">edit</a>)
    {% endif %}
</h1>
<p>{{ album.description }}</p>
{% if album.image %}
    <p><img src="{{ album.image.url }}"/></p>
{% endif %}
<p>Served by <a href="{% url 'myrecommendations:artist_detail' album.artist.id %}">{{ album.artist.name }}</a></p>

{% endblock %}

{% block footer %}
    Created by {{ album.user }} on {{ album.date }}
{% endblock %}

myartists/templates/myartists/artist_detail.html
{% extends "myrecommendations/base.html" %}

{% block title %}MyArtists - {{ artist.name }}{% endblock %}

{% block content %}

<span vocab="http://schema.org/" typeof="Artist">
<h1>
    <span property="name">{{ artist.name }}</span>
    {% if user == artist.user %}
        (<a href="{% url 'myrecommendations:artist_edit' artist.id %}">edit</a>)
    {% endif %}
</h1>

<h2>Address:</h2>
<p>
    {{ artist.street }}, {{ artist.number }} <br/>
    {{ artist.zipcode }} {{ artist.city }} <br/>
    {{ artist.stateOrProvince }} ({{ artist.country }})
</p>

<h2>
    Albums
    {% if user %}
        (<a href="{% url 'myrecommendations:dish_create' artist.id %}">add</a>)
    {% endif %}
</h2>
<ul>
    {% for dish in artist.albums.all %}
        <li><a href="{% url 'myrecommendations:dish_detail' artist.id dish.id %}">{{ dish.name }}</a></li>
    {% empty %}
        <li>Sorry, no albums for this artist yet.</li>
    {% endfor %}
</ul>

<h2>Reviews</h2>
{% if artist.artistreview_set.all|length > 0 %}
<span rel="aggregateRating">
    <p typeof="AggregateRating">
        Average rating <span property="ratingValue">{{ artist.averageRating|stringformat:".1f" }}</span>
        {% with artist.artistreview_set.all|length as reviewCount %}
        from <span property="reviewCount">{{ reviewCount }}</span> review{{ reviewCount|pluralize }}
        {% endwith %}
    </p>
</span>
<ul rel="review">
    {% for review in artist.artistreview_set.all %}
        <li typeof="Review">
            <p rel="reviewRating" typeof="Rating">
                <span property="worstRating" content="{{ RATING_CHOICES.0.0 }}"></span>
                <span property="ratingValue">{{ review.rating }}</span> star{{ review.rating|pluralize }}
                {% with RATING_CHOICES|last as best %}
                <span property="bestRating" content="{{ best.0 }}"></span>
                {% endwith %}
            </p>
            <p property="description">{{ review.comment }}</p>
            <p>Created by <span property="author">{{ review.user }}</span> on
                <span property="publishDate">{{ review.date}}</span></p>
        </li>
    {% endfor %}
</ul>
</span>
{% endif %}

<h3>Add Review</h3>
<form action="{% url 'myrecommendations:review_create' artist.id %}" method="post">
    {% csrf_token %}
    Message: <textarea name="comment" id="comment" rows="4"></textarea>
    <p>Rating:</p>
    <p>
    {% for rate in RATING_CHOICES %}
        <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ rate.1 }}" />
        <label for="choice{{ forloop.counter }}">{{ rate.1 }} star{{ rate.0|pluralize }}</label><br />
    {% endfor %}
    </p>
    <input type="submit" value="Review" />
</form>

{% endblock %}

{% block footer %}
    Created by {{ artist.user }} on {{ artist.date }}
{% endblock %}

myartists/templates/myartists/artist_list.html
{% extends "myrecommendations/base.html" %}

{% block content %}

<h1>
    Artists
    {% if user %}
        (<a href="{% url 'myrecommendations:artist_create' %}">add</a>)
    {% endif %}
</h1>

<ul>
    {% for artist in latest_artist_list %}
        <li><a href="{% url 'myrecommendations:artist_detail' artist.id %}">{{ artist.name }}</a></li>
    {% empty %}
        <li>Sorry, no artists registered yet.</li>
    {% endfor %}
</ul>

{% endblock %}

myartists/templates/myartists/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static "style/base.css" %}" />
    <title>{% block title %}MyArtists by MyRecommentdations.org{% endblock %}</title>
</head>

<body>

<div id="header">
    {% block header %}
        {% if user.username %}
            <p>User {{ user.username }} (<a href="/accounts/logout/?next=/myartists/">logout</a>)</p>
        {% else %}
            <p><a href="/accounts/login/?next=/myartists/">Sign in</a></p>
        {% endif %}
    {% endblock %}
</div>


<div id="sidebar">
    {% block sidebar %}
        <ul>
            <li><a href="/myrecommendations/">Home</a></li>
        </ul>
    {% endblock %}
</div>

<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>

<div id="footer">
    {% block footer %}{% endblock %}
</div>

</body>
</html>

myartists/templates/myartists/form.html
{% extends "myrecommendations/base.html" %}
{% load staticfiles %}

{% block content %}

    <script>
        $(function() {
            $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_country").autocomplete({
                    source: countries
                });
            });

            $("#id_city").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://api.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term,
                            username: "demo"
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
                                    stateOrProvince: item.adminName1,
                                    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
                select: function( event, ui ) {
                    if (ui.item) {
                        $("#id_stateOrProvince").val(ui.item.stateOrProvince);
                        $("#id_country").val(ui.item.countryName);
                        $("#id_zipCode").val("");
                    }
                }
            });
        });
    </script>

    <form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar"/>
    </form>

{% endblock %}

myartists/templates/myartists/song_detail.html
{% extends "myrecommendations/base.html" %}

{% block content %}

<h1>
    {{ song.name }}
    {% if user == song.user %}
        (<a href="{% url 'myrecommendations:song_edit' song.artist.id song.id %}">edit</a>)
    {% endif %}
</h1>
<p>{{ song.description }}</p>
<p>Served by <a href="{% url 'myrecommendations:artist_detail' song.artist.id %}">{{ song.artist.name }}</a></p>

{% endblock %}

{% block footer %}
    Created by {{ song.user }} on {{ song.date }}
{% endblock %}